LabaManage.WebMVC/Controllers/JournalController.cs
using System.Web.Mvc;
using LabaManage.BLL.Abstract;
using LabaManage.Models.Models;
using LabaManage.WebMVC.ViewModels.Journal;
using LabaManage.WebMVC.ViewModels.TeachPlan;

namespace LabaManage.WebMVC.Controllers
{
    [Authorize(Roles = "Teachers")]
    public class JournalController : Controller
    {
        private const int PageSize = 10;
        private const int DefaultPage = 1;
        private ILessonRepository lessonRepository;
        private IUserRepository userRepository;

        public JournalController(ILessonRepository repoL, IUserRepository repoU)
        {
            this.lessonRepository = repoL;
            this.userRepository = repoU;
        }

        public ActionResult List()
        {
            ListViewModel model = new ListViewModel { Courses = this.lessonRepository.Courses };
            return this.View(model);
        }

        public ActionResult Edit(int courseId, int page = DefaultPage)
        {
            JournalEditModel model = new JournalEditModel
                {
                    Course = this.lessonRepository.GetCourseById(courseId),
                    Lessons = this.lessonRepository.GetLessonsByCourse(courseId, page, PageSize),
                    Users = this.userRepository.GetUsersInRole("Students"),
                    PagingInfo = 
                    new PagingInfo
                    {
                        CurrentPage = page,
                        TotalItems = this.lessonRepository.LessonsCountByCourse(courseId),
                        ItemsPerPage = PageSize
                    }
            };
            return this.View(model);
        }

        [HttpPost]
        public void AddUserMissLesson()
        {
            var userId = Request.Form.GetValues("userId")[0];
            var lessonId = Request.Form.GetValues("lessonId")[0];
            var userLesson = new UserLesson(lessonId, userId);
            this.lessonRepository.AddUserMissLesson(userLesson);
        }

        [HttpPost]
        public void RemoveUserMissLesson()
        {
            var userId = Request.Form.GetValues("userId")[0];
            var lessonId = Request.Form.GetValues("lessonId")[0];
            var userLesson = new UserLesson(lessonId, userId);
            this.lessonRepository.RemoveUserMissLesson(userLesson);
        }
    }
}

LabaManage.WebMVC/Controllers/RoleController.cs
using System.Web.Mvc;
using LabaManage.BLL.Abstract;
using LabaManage.Models.Models;
using LabaManage.WebMVC.ViewModels.Role;

namespace LabaManage.WebMVC.Controllers
{
    [Authorize(Roles = "Administrators")]
    public class RoleController : Controller
    {
        private IUserRepository repository;

        public RoleController(IUserRepository repo)
        {
            this.repository = repo;
        }

        public ViewResult List()
        {
            ListViewModel roles = new ListViewModel { Roles = this.repository.Roles };
            return this.View(roles);
        }

        public ViewResult Edit(int roleId)
        {
            EditViewModel viewRole = new EditViewModel { Role = this.repository.GetRoleById(roleId) };
            return this.View(viewRole);
        }

        [HttpPost]
        public ActionResult Edit(RoleModel role)
        {
            if (ModelState.IsValid)
            {
                this.repository.RoleUpdate(role);
                this.TempData["message"] = string.Format("Изменения в роли \"{0}\" были сохранены", role.Name);
                return this.RedirectToAction("List");
            }
            else
            {
                return this.View(role);
            }
        }

        public ViewResult Create()
        {
            return this.View("Edit", new EditViewModel { Role = new RoleModel() });
        }

        [HttpPost]
        public ActionResult Delete(int roleId)
        {
            if (!this.repository.AreUsersInRole(roleId))
            {
                RoleModel deletedRole = this.repository.RoleDelete(roleId);
                if (deletedRole != null)
                {
                    this.TempData["message"] = string.Format("Роль \"{0}\" успешно удалена.", deletedRole.Name);
                }
            }
            else
            {
                this.TempData["message"] = string.Format("Роль \"{0}\" нельзя удалить пока есть пользователи в этой роли.", this.repository.GetRoleById(roleId).Name);
            }

            return this.RedirectToAction("List");
        }
    }
}

LabaManage.WebMVC/Controllers/TeachPlanController.cs
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using LabaManage.BLL.Abstract;
using LabaManage.Models.Models;
using LabaManage.WebMVC.ViewModels.TeachPlan;

namespace LabaManage.WebMVC.Controllers
{
    [Authorize(Roles = "Teachers")]
    public class TeachPlanController : Controller
    {
        private ILessonRepository repository;
        
        public TeachPlanController(ILessonRepository repo)
        {
            this.repository = repo;
        }

        public ActionResult List()
        {
            ListViewModel model = new ListViewModel { Courses = this.repository.Courses };
            return this.View(model);
        }

        public ActionResult Edit(int courseId)
        {
            var dates = this.repository.GetDatesByCourse(courseId).Select(x => x.ToString("yyyy-MM-dd hh:mm:ss")).ToArray();
            EditViewModel course = new EditViewModel
            {
                Course = this.repository.GetCourseById(courseId),
                Dates = string.Join(",", dates)
            };
            return this.View(course);
        }

        [HttpPost]
        public ActionResult Edit(EditViewModel courseModel)
        {
            CultureInfo provider = CultureInfo.InvariantCulture;
            if (ModelState.IsValid)
            {
                this.repository.CourseUpdate(courseModel.Course, courseModel.GetArrayDates());
                this.TempData["message"] = string.Format("Изменения в курсе \"{0}\" были сохранены", courseModel.Course.Name);
                return this.RedirectToAction("List");
            }
            else
            {
                return this.View(new EditViewModel
                {
                    Course = courseModel.Course
                });
            }
        }

        public ViewResult Create()
        {
            return this.View("Edit", new EditViewModel { Course = new CourseModel() });
        }

        [HttpPost]
        public ActionResult Delete(int courseId)
        {
           CourseModel deletedCourse = this.repository.CourseDelete(courseId);
           if (deletedCourse != null)
              {
                this.TempData["message"] = string.Format("Курс \"{0}\" успешно удален.", deletedCourse.Name);
              }

            return this.RedirectToAction("List");
        }
    }
}

LabaManage.WebMVC/Controllers/UserController.cs
using System.Web.Mvc;
using LabaManage.BLL.Abstract;
using LabaManage.Models.Models;
using LabaManage.WebMVC.Abstract;
using LabaManage.WebMVC.ViewModels.User;

namespace LabaManage.WebMVC.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private const int PageSize = 5;
        private const int DefaultPage = 1;
        private IUserRepository repository;
        private ILogger log;

        public UserController(IUserRepository repo, ILogger log)
        {
            this.log = log;
            this.repository = repo;
        }

        public ViewResult List(int page = DefaultPage)
        {
            ListViewModel model = new ListViewModel
            {
                Users = this.repository.GetUserList(page, PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    TotalItems = this.repository.GetUsersCount(),
                    ItemsPerPage = PageSize
                }
            };
            return this.View(model);
        }

        [Authorize(Roles = "Administrators")]
        public ViewResult Edit(int userId)
        {
            EditViewModel model = new EditViewModel
            {
                User = this.repository.GetUserById(userId),
                Roles = this.repository.Roles
            };
            return this.View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public ActionResult Edit(UserModel user)
        {
            if (ModelState.IsValid)
            {
                var message = "User " + user.Name + ((user.UserId == 0) ? " created" : " edited");
                this.repository.UserUpdate(user);
                this.TempData["message"] = string.Format("Изменения в пользователе \"{0}\" были сохранены", user.Name);
                this.log.Info(message);
                return this.RedirectToAction("List");
            }
            else
            {
                return this.View(new EditViewModel
                {
                    User = user,
                    Roles = this.repository.Roles
                });
            }
        }

        [Authorize(Roles = "Administrators")]
        public ViewResult Create()
        {
            var model = new EditViewModel
            {
                User = new UserModel { RoleId = this.repository.GetFirstRole().RoleId },
                Roles = this.repository.Roles
            };

            return this.View("Edit", model);
        }

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public ActionResult Delete(int userId)
        {
            UserModel deletedUser = this.repository.UserDelete(userId);
            if (deletedUser != null)
            {
                this.TempData["message"] = string.Format("Пользователь \"{0}\" успешно удален.", deletedUser.Name);
            }

            return this.RedirectToAction("List");
        }
    }
}

LabaManage.WebMVC/Views/Shared/ErrorPage.cshtml
@model HandleErrorInfo
@{
    //Layout = null;
    ViewBag.Title = "Извините, возникли проблемы!";
}

<h2>Извините</h2>
<span>
    <b>Возникло непредвиденное событие. Обратитесь пожалуйста к администратору сайта.</b>
</span>
<div>
    @Html.ActionLink("Вернуться обратно", "Index", "Home")
</div>

LabaManage.WebMVC/Views/Shared/TaskSummary.cshtml
@model LabaManage.WebMVC.ViewModels.Task.TaskViewModel
@using LabaManage.WebMVC.HtmlHelpers

<div class="well">
    <div class="btn-group pull-right">
        @using (Html.BeginForm("Delete", "TaskManage"))
        {
            @Html.ActionLink("Изменить", "Edit", new { Model.Task.TaskId }, new { @class = "btn btn-primary hidden-xs" })
            @Html.ActionLink(" ", "Edit", new { Model.Task.TaskId }, new { @class = "btn btn-primary glyphicon glyphicon-edit visible-xs" })
            @Html.Hidden("TaskId", Model.Task.TaskId)
            <input type="submit"
                   class="btn btn-danger hidden-xs"
                   value="Удалить" />
            <button type="submit" formmethod="post" class="btn btn-danger glyphicon glyphicon-remove visible-xs"></button>
        }
    </div>
    <h4>Тема: @Model.Task.Topic уровень: @Model.Task.Level автор: @Model.Task.Author</h4>
    <h4>@Model.Task.Name</h4>
    <div class="well" id="@string.Format($"textwellp{Model.Task.TaskId}")" style="display:block">
        <div class="hidden-xs" style="float: right;">
            @for (int i = 5; i >= 1; i--)
            {
                <div style="display:inherit">
                    <div style="display:inline-flex;">
                        <ul class="rating" style="display:inherit">
                            @Html.Stars(i);
                        </ul>
                        <span style="display:inherit">@string.Format($" - {Model.PercentFeature[i - 1]}%")</span>
                    </div>
                </div>
            }
        </div>
        <div>
            <ul class="rating">
                @Html.Stars(Model.AvgRating);
            </ul>
        </div>

        <p>@Model.AvgRating</p>
        <span>@Model.Task.Text.Substring(0, 10)</span> 
        <button id="@string.Format($"f{Model.Task.TaskId}")" class="btn btn-default btn-sm hidden-xs">...</button>
        <button id="@string.Format($"f{Model.Task.TaskId}")" class="btn btn-default glyphicon glyphicon-arrow-down visible-xs"></button>
        <br />
        <br />
        @foreach (var tag in Model.Task.Tags)
        {
            <button id="@string.Format($"t{tag.TagId}")" class="btn btn-info btn-sm hidden-xs" name="@tag.Name">@tag.Name</button>
        }
    </div>
    <div class="well" id="@string.Format($"textwellf{Model.Task.TaskId}")" style="display:none">
        <div>
            <button id="@string.Format($"p{Model.Task.TaskId}")" class="btn btn-default hidden-xs" style="float: right; vertical-align:top">Свернуть</button>
            <button id="@string.Format($"p{Model.Task.TaskId}")" class="btn btn-default glyphicon glyphicon-arrow-up visible-xs" style="float: right; vertical-align:top"></button>
        </div>
        <br />
        <div>@Model.Task.Text</div>
        <br />
        @foreach (var tag in Model.Task.Tags)
        {
            <button id="@string.Format($"t{tag.TagId}")" class="btn btn-info btn-sm hidden-xs" name="@tag.Name">@tag.Name</button>
        }
        <br />
        <div id="@string.Format($"coment{Model.Task.TaskId}")"></div>
    </div> 
</div>

LabaManage.WebMVC/Views/Shared/_AdminLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</div>

LabaManage.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LabaManageSystem</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container">
        <!-- Классы navbar и navbar-default (базовые классы меню) -->
        <nav class="navbar navbar-inverse">
            <!-- Контейнер (определяет ширину Navbar) -->
            <div class="container-fluid">
                <!-- Заголовок -->
                <div class="navbar-header">
                    <!-- Кнопка «Гамбургер» отображается только в мобильном виде (предназначена для открытия основного содержимого Navbar) -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main" aria-expanded="false" aria-controls="navbar-main">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Бренд или название сайта (отображается в левой части меню) -->
                    <a class="nav navbar-brand" href="@Url.Action("Index", "Home")">
                        <span class="hidden-xs">LabaManage</span>
                        <span class="glyphicon glyphicon-home visible-xs" data-toggle="tooltip" title="LabaManage"></span>
                    </a>
                </div>
                <!-- Основная часть меню (может содержать ссылки, формы и другие элементы) -->
                <div class="collapse navbar-collapse" id="navbar-main">
                    <!-- Содержимое основной части -->
                    <ul class="nav navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Пользователи", "List", "User", new { area = "" }, new { @class = "btn" })</li>
                        }
                        @if (User.IsInRole("Administrators"))
                        {
                            <li>@Html.ActionLink("Роли", "List", "Role", new { area = "" }, new { @class = "btn" })</li>
                        }
                        @if (User.IsInRole("Teachers"))
                        {
                            <li>@Html.ActionLink("Учебный план", "List", "TeachPlan", new { area = "" }, new { @class = "btn" })</li>
                            <li>@Html.ActionLink("Журнал посещаемости", "List", "Journal", new { area = "" }, new { @class = "btn" })</li>
                            <li>@Html.ActionLink("База заданий", "List", "TaskManage", new { area = "" }, new { @class = "btn" })</li>
                        }
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink(User.Identity.Name, "#")</li>
                            <li>@Html.ActionLink("Выход", "Logoff", "Account", new { area = "" }, new { @class = "btn" })</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Логин", "Login", "Account", new { area = "" }, new { @class = "btn" })</li>
                            <li>@Html.ActionLink("Регистрация", "Register", "Account", new { area = "" }, new { @class = "btn" })</li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container body-content" id="container" data-request-tags-url="@Url.Action("GetTagsDataJson", "TaskManage")">
            <div>
                @if (TempData["message"] != null)
            {
                    <div class="alert alert-success">@TempData["message"]</div>
                }
                @RenderBody()
            </div>
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - LabaManageSystem</p>
            </footer>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/tokens")
        @RenderSection("Scripts", false)
</div>
</body>
</html>