LabaManage.WebMVC/ViewModels/Task/EditViewModel.cs
using LabaManage.Models.Models;

namespace LabaManage.WebMVC.ViewModels.Task
{
    public class EditViewModel
    {
        public TaskModel Task { get; set; }
    }
}

LabaManage.WebMVC/ViewModels/Task/ListViewModel.cs
using System.Collections.Generic;
using System.Linq;
using LabaManage.Models.Models;

namespace LabaManage.WebMVC.ViewModels.Task
{
    public class ListViewModel
    {
        public IEnumerable<TaskViewModel> Tasks { get; set; }

        public FilterListsModel Lists { get; set; }

        public FilterModel Filter { get; set; }

        public PagingInfo PagingInfo { get; set; }

        public void SetTotalItems()
        {
            this.PagingInfo.TotalItems = this.Tasks.Count();
        }
    }
}

LabaManage.WebMVC/Controllers/TaskLoadController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LabaManage.BLL.Abstract;
using LabaManage.Models.Models;
using LabaManage.XML.Abstract;

namespace LabaManage.WebMVC.Controllers
{
    [Authorize(Roles = "Teachers")]
    public class TaskLoadController : Controller
    {
        private IxmlProcessor processor;
        private ITaskRepository repository;

        public TaskLoadController(IxmlProcessor proc, ITaskRepository repo)
        {
            this.processor = proc;
            this.repository = repo;
        }

        public ActionResult Index()
        {
            return this.View();
        }

        public ActionResult Downloadfile()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory + "uploads/";
            string fileName = "tasks.xml";

            var tasks = this.repository.Tasks.ToList();
            this.processor.DownloadTasksToFile(tasks, path + fileName);
            return this.File(path + fileName, "text/xml", fileName);
        }

        [HttpPost]
        public ActionResult Uploadfile(HttpPostedFileBase xmlfile = null)
        {
            if (xmlfile != null && xmlfile.ContentLength > 0 && xmlfile.ContentType == "text/xml")
            {
                var tasks = this.processor.UploadTasksFromFile(xmlfile.InputStream);
                var result = this.repository.TaskAddAll(tasks.Select(_ =>
                new TaskModel
                {
                    TaskId = _.TaskId,
                    Author = _.Author,
                    Level = _.Level,
                    Topic = _.Topic,
                    Name = _.Name,
                    Text = _.Text
                }).ToList());
                var innerMessage = (!result.IsSucceed) ? string.Format(
                    ". Не сохранены следующие задания: {0}",
                    string.Join(",", result.NonCommited.Select(_ => _))) : string.Empty;
                this.TempData["message"] = string
                    .Format("Загружены {0} из {1} заданий{2}.", result.SucceededItems, tasks.Count(), innerMessage);
                return this.RedirectToAction("List", "TaskManage");
            }
            else
            {
                this.TempData["message"] = "Задания не были загружены! Неверный формат файла.";
                return this.RedirectToAction("Index");
            }
        }
    }
}

LabaManage.WebMVC/Controllers/TaskManageController.cs
using System.Linq;
using System.Web.Mvc;
using LabaManage.BLL.Abstract;
using LabaManage.Models.Models;
using LabaManage.WebMVC.ViewModels.Task;

namespace LabaManage.WebMVC.Controllers
{
    [Authorize(Roles = "Teachers")]
    public class TaskManageController : Controller
    {
        private const int PageSize = 5;
        private const int DefaultPage = 1;
        private ITaskRepository repository;

        public TaskManageController(ITaskRepository repo)
        {
            this.repository = repo;
        }

        public ViewResult List(FilterModel filter, int page = DefaultPage)
        {
            ListViewModel model = 
                new ListViewModel
                {
                    Tasks = this.repository.GetTasksByFilter(filter, page, PageSize)
                    .Select(_ => new TaskViewModel
                    {
                        Task = _,
                        PercentFeature = this.repository.GetRatingsByTaskPercents(_.TaskId),
                        RatingsCount = this.repository.GetRatingsByTaskCount(_.TaskId),
                        AvgRating = this.repository.GetAvgRatingByTaskId(_.TaskId)
                    }),
                    Filter = filter,
                    Lists = this.repository.GetFilterLists(),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalItems = this.repository.GetTasksCount(filter)
                    }
                };
            return this.View(model);
        }

        public ActionResult GetTaskComentsJson(int taskId)
        {
            var result = Json(
                new ComentListJson
                {
                    Ratings = this.repository.GetRatingsByTask(taskId, DefaultPage, PageSize).ToList(),
                    CurrentUserRating = this.repository.GetRatingByTaskUser(User.Identity.Name, taskId)
                },
                JsonRequestBehavior.AllowGet);
            return result;
        }

        [HttpPost]
        public void DeleteComment(int commentId)
        {
            this.repository.RatingDelete(commentId);
        }

        [HttpPost]
        public void SaveComment(RatingModel rating)
        {
            int i = 1;
            if (ModelState.IsValid)
            {
                i = i + 1;
                this.repository.RatingUpdate(rating);
            }
        }

        public ActionResult GetTasksDataJson(FilterModel filter, string author, string topic, string level, string tags)
        {
            filter.Level = (level == string.Empty) ? 0 : (level != null) ? int.Parse(level) : filter.Level;
            filter.Author = (author == string.Empty) ? string.Empty : author ?? filter.Author;
            filter.Topic = (topic == string.Empty) ? string.Empty : topic ?? filter.Topic;
            filter.Tags = (tags == string.Empty) ? string.Empty : tags ?? filter.Tags;
            int totalItems = this.repository.GetTasksCount(filter);
            int totalPages = totalItems / PageSize;
            if ((totalItems % PageSize) > 0)
            {
                totalPages++;
            }

            if (totalPages > 3)
            {
                totalPages = 3;
            }

            var result = Json(
                new ListJsonModel
                {
                    TotalPages = totalPages,
                    Tasks = this.repository.GetTasksByFilter(filter, DefaultPage, PageSize)
                    .Select(_ => new TaskViewModel
                    {
                        Task = _,
                        PercentFeature = this.repository.GetRatingsByTaskPercents(_.TaskId),
                        RatingsCount = this.repository.GetRatingsByTaskCount(_.TaskId),
                        AvgRating = this.repository.GetAvgRatingByTaskId(_.TaskId)
                    })
                },
                JsonRequestBehavior.AllowGet);
            return result;
        }

        public ActionResult GetTagsDataJson(string text)
        {
            var result = Json(
                this.repository.GetTags(text).Select(_ => new { value = _.Name, label = _.Name }).ToList(),
                JsonRequestBehavior.AllowGet);
            return result;
        }

        public ViewResult Edit(int taskId)
        {
            EditViewModel model = new EditViewModel
            {
                Task = this.repository.GetTaskById(taskId)
            };
            return this.View(model);
        }

        [HttpPost]
        public ActionResult Edit(TaskModel task)
        {
            if (ModelState.IsValid)
            {
                if (this.repository.GetTaskByName(task.Name) != null && task.TaskId == 0)
                {
                    this.TempData["message"] = string.Format("Нельзя сохранить, задание с таким наименованием уже есть.");
                }
                else
                {
                    this.repository.TaskUpdate(task);
                    this.TempData["message"] = string.Format("Изменения в задании были сохранены.");
                    return this.RedirectToAction("List");
                }
            }

            return this.View(new EditViewModel
            {
                Task = task
            });
        }

        public ViewResult Create()
        {
            var model = new EditViewModel
            {
                Task = new TaskModel()
            };
            return this.View("Edit", model);
        }

        [HttpPost]
        public ActionResult Delete(int taskId)
        {
            TaskModel deletedTask = this.repository.TaskDelete(taskId);
            if (deletedTask != null)
            {
                this.TempData["message"] = string.Format("Задание успешно удалено.");
            }

            return this.RedirectToAction("List");
        }
    }
}

LabaManage.WebMVC/Views/TaskManage/Edit.cshtml
@model LabaManage.WebMVC.ViewModels.Task.EditViewModel
@{
    ViewBag.Title = "Панель: редактирование заданий";
}
<style>
    .twitter-typeahead .tt-hint {
  border: 0;
  padding: 0;
}

.tt-dropdown-menu {
  min-width: 160px;
  margin-top: 2px;
  padding: 5px 0;
  background-color: #fff;
  border: 1px solid #ccc;
  border: 1px solid rgba(0,0,0,.2);
  *border-right-width: 2px;
  *border-bottom-width: 2px;
  -webkit-border-radius: 6px;
     -moz-border-radius: 6px;
          border-radius: 6px;
  -webkit-box-shadow: 0 5px 10px rgba(0,0,0,.2);
     -moz-box-shadow: 0 5px 10px rgba(0,0,0,.2);
          box-shadow: 0 5px 10px rgba(0,0,0,.2);
  -webkit-background-clip: padding-box;
     -moz-background-clip: padding;
          background-clip: padding-box;
}

.tt-suggestion {
  display: block;
  padding: 3px 20px;
}

.tt-suggestion.tt-is-under-cursor {
  color: #fff;
  background-color: #0081c2;
  background-image: -moz-linear-gradient(top, #0088cc, #0077b3);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#0088cc), to(#0077b3));
  background-image: -webkit-linear-gradient(top, #0088cc, #0077b3);
  background-image: -o-linear-gradient(top, #0088cc, #0077b3);
  background-image: linear-gradient(to bottom, #0088cc, #0077b3);
  background-repeat: repeat-x;
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff0088cc', endColorstr='#ff0077b3', GradientType=0)
}

.tt-suggestion.tt-is-under-cursor a {
  color: #fff;
}

.tt-suggestion p {
  margin: 0;
}
</style>
<div class="panel panel-primary">
    <div class="panel-heading">
        @if (Model.Task.Name != null && Model.Task.Name != string.Empty)
        {
            <h3> Редактируем задание - "@Model.Task.Name"</h3>
        }
        else
        {
            <h3> Добавляем новое задание</h3>
        }
    </div>
    @Html.ValidationSummary(false)
    @using (Html.BeginForm("Edit", "TaskManage"))
    {
        <div class="panel-body">
            <div> <p>@Html.HiddenFor(_ => _.Task.TaskId)</p> </div>
            <div class="form-group">
                <p>@Html.LabelFor(_ => _.Task.Author)</p>
                <div>
                    <p>@Html.EditorFor(_ => _.Task.Author)</p>
                </div>
            </div>
            <div class="form-group">
                <p>@Html.LabelFor(_ => _.Task.Topic)</p>
                <div>
                    <p>@Html.EditorFor(_ => _.Task.Topic)</p>
                </div>
            </div>
            <div class="form-group">
                <p>@Html.LabelFor(_ => _.Task.Level)</p>
                <div>
                    <p>@Html.EditorFor(_ => _.Task.Level)</p>
                </div>
            </div>
            <div class="form-group">
                <p>@Html.LabelFor(_ => _.Task.Name)</p>
                <div>
                    <p>@Html.EditorFor(_ => _.Task.Name)</p>
                </div>
            </div>
           <div class="form-group">
                <p>@Html.LabelFor(_ => _.Task.Text)</p>
                <div>
                    @Html.TextAreaFor(_ => _.Task.Text, new { @class = "form-control", rows = 5 })
                </div>
            </div>
            <div class="form-group">
                <input name="Task.TagString" type="text" class="form-control" id="tokenfield" value="@Model.Task.TagString" />
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отменить изменения и вернуться к списку", "List", null, new
           {
               @class = "btn btn-default"
           })
        </div>
    }
</div>

@section scripts{
<script type="text/javascript">
    $("#tokenfield").focus(function () {
        var url = $("#container").data('request-tags-url');
        var text = $("#Task_Text").val() + $("#Task_Name").val();
        TagsAjax(url, text);
    });
</script>
}

LabaManage.WebMVC/Views/TaskManage/List.cshtml
@model LabaManage.WebMVC.ViewModels.Task.ListViewModel
@using LabaManage.WebMVC.HtmlHelpers
@{
    ViewBag.Title = "Список заданий";
}
<br />
<div class="panel panel-primary">
    <div class="panel-heading">
     <h3> Список заданий </h3>
        <div>
            <div class="form-group">
                <input type="text" class="form-control" id="tokenfield" value="@Model.Filter.Tags" />
            </div>
        </div>
    </div>
        <div class="btn-group pull-right">
            @Html.ActionLink("Добавить задание", "Create", "TaskManage", new { area = "" }, new { @class = "btn btn-primary hidden-xs" })
            @Html.ActionLink("Загрузить задания", "Index", "TaskLoad", new { area = "" }, new { @class = "btn btn-primary hidden-xs" })
            @Html.ActionLink("Скачать задания", "DownloadFile", "TaskLoad", new { area = "" }, new { @class = "btn btn-primary hidden-xs" })
            @Html.ActionLink(" ", "Create", "TaskManage", new { area = "" }, new { @class = "btn btn-primary glyphicon glyphicon-plus visible-xs" })
            @Html.ActionLink(" ", "Index", "TaskLoad", new { area = "" }, new { @class = "btn btn-primary glyphicon glyphicon-upload visible-xs" })
            @Html.ActionLink(" ", "DownloadFile", "TaskLoad", new { area = "" }, new { @class = "btn btn-primary glyphicon glyphicon-download visible-xs" })
        </div>
        <div class="panel-body">
            <div style="display:inline-flex">
                <span class="hidden-xs">Автор:</span>
                <span class="visible-xs glyphicon glyphicon-user"></span>
                @Html.DropDownListFor(_ => _.Filter.Author, new SelectList(Model.Lists.Authors.ToList(), "all"), "all", new { @class = "dropdown" })
                <span class="hidden-xs">Тема:</span>
                <span class="visible-xs glyphicon glyphicon-bookmark"></span>
                @Html.DropDownListFor(_ => _.Filter.Topic, new SelectList(Model.Lists.Topics.ToList(), "all"), "all", new { @class = "dropdown" })
                <span class="hidden-xs">Уровень сложности:</span>
                <span class="visible-xs glyphicon glyphicon-scale"></span>
                @Html.DropDownListFor(_ => _.Filter.Level, new SelectList(Model.Lists.Levels.ToList(), "all"), "all", new { @class = "dropdown" })
            </div>
            <div id="TasksList"
                 data-request-tasks-url="@Url.Action("GetTasksDataJson")?"
                 data-request-comments-url="@Url.Action("GetTaskComentsJson")?taskId="
                 data-request-taskdelete-url="@Url.Action("Delete", "TaskManage")"
                 data-request-taskedit-url="@Url.Action("Edit", "TaskManage")?TaskId="
                 data-request-commentdelete-url="@Url.Action("DeleteComment","TaskManage")"
                 data-request-commentsave-url="@Url.Action("SaveComment","TaskManage")"
                 data-request-tags-url="@Url.Action("GetTagsDataJson", "TaskManage")">
                @foreach (var p in @Model.Tasks)
            {
                    @Html.Partial("TaskSummary", p);
            }
            </div>
        </div>
        <div id="ButtonsGroup" class="btn-group pull-right">
            @Html.PageLinks(Model.PagingInfo, _ => Url.Action("List", new { page = _, filter = Model.Filter }))
        </div>
    </div>

@section scripts{
    @Scripts.Render("~/bundles/taskrating")
}